server:
  port: 8002
  servlet:
    context-path: /process

spring:
  profiles:
    active: dev
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.188.128:9000
  zipkin:
    base-url: http://192.168.188.128:9411

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
