server:
  port: 8001
  servlet:
    context-path: /system

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://192.168.188.128:3306/oa?characterEncoding=utf8&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  cloud:
    sentinel:
      transport:
        dashboard: 192.168.188.128:9000
#      datasource:
#        ds1:
#          nacos:
#            server-addr: 192.168.188.128:8848
#            namespace: 11d3dec1-9300-4536-83ce-743764d4ce67
#            data-id: oa-service-system-flow-rules
#            data-type: json
#            ruleType: flow
#        ds2:
#          nacos:
#            server-addr: 192.168.188.128:8848
#            namespace: 11d3dec1-9300-4536-83ce-743764d4ce67
#            data-id: oa-service-system-system-rules
#            data-type: json
#            ruleType: system

    alibaba:
      seata:
        tx-service-group: /system-service

  redis:
    host: 192.168.188.128
    port: 6379

  zipkin:
    base-url: http://192.168.188.128:9411

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
seata:
  service:
    disable-global-transaction: false
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.188.128
      namespace: 11d3dec1-9300-4536-83ce-743764d4ce67
      application: seata-server
      group: SEATA_GROUP
      cluster: default
  config:
    type: nacos
    nacos:
      server-addr: 192.168.188.128
      namespace: 6543b661-c9c4-4123-b39e-dcd74d130ed1
      group: SEATA_GROUP
